heat_template_version: 2016-04-08
## cli deploy $ openstack stack create --template heat-minipoc.yaml mini-poc
description: >
  HOT template to create 2 neutron networks, 2 generic VMs a Fortios VM
  in between and floating ip for everyone.
  Used for experimenting Fortinet in a cloud environment.
  
parameters:
 fgtimage:
  type: string
  description: Fortios image
  default: "fgt54"
 ubimage:
  type: string
  description: Ubuntu image
  default: "Trusty x86_64"
 mgmt_net:
  type: string
  description: My private network
  default: "mgmt"
 public_net:
  type: string
  description: External network for floating ips
  default: "ext_net"


resources:
 left_net:
    type: OS::Neutron::Net
    properties:
      name: "left"

 left_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: left_net }
      cidr: "10.40.40.0/24"
      allocation_pools:
        - start: "10.40.40.3"
          end:  "10.40.40.250"
      host_routes: [{"nexthop": "10.40.40.254", "destination": "10.20.20.0/24"}]
 
 right_net:
    type: OS::Neutron::Net
    properties:
      name: "right"

 right_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: right_net }
      cidr: "10.20.20.0/24"
      allocation_pools:
        - start: "10.20.20.3"
          end:  "10.20.20.250"

 fgt_left_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: left_net }
      port_security_enabled: false
      fixed_ips:
        - ip_address: "10.40.40.254"

 fgt_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }


 fgt:
  type: OS::Nova::Server
  properties:
   image: { get_param: fgtimage }
   flavor: m1.small
   user_data_format: RAW
   user_data: |
                config system interface
                edit port1
                 set mode dhcp
                 set allowaccess ping https ssh http snmp fgfm
                 set mtu-override enable 
                 set mtu 1456
                 set defaultgw enable
                next
                edit port2
                 set mode dhcp
                 set mtu-override enable 
                 set mtu 1456
                 set allowaccess ping
                 set defaultgw disable
                next
                edit port3
                 set mode dhcp
                 set mtu-override enable 
                 set mtu 1456
                 set allowaccess ping
                 set defaultgw disable
                next
                end
                config system dns
                set primary 8.8.8.8
                end
                config firewall policy
                edit 1
                set name "Allow any any"
                set srcintf "any"
                set dstintf "any"
                set srcaddr "all"
                set dstaddr "all"
                set action accept
                set schedule "always"
                set service "ALL"
                set nat enable
                next
                end
   name: FGT
   config_drive: True
   user_data_format: RAW
#   personality: {"license":
#  -----BEGIN FGT VM LICENSE-----
#  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#  KQkV+M0QnaPNeflgAAAAuK74PkXL6V33n2WaYUEb9S981Xoo6hjuF4EUAwbgJKL/v3ZF0doXylw2
#  oXben61XZpvip3cwZfbeQuaa5Vmt+SnBH7GZPkBGQSbuSXqjJHB+/iq4naP8h1t05yWhHlRM
#  -----END FGT VM LICENSE-----}
   personality: {"license": { get_file: FGT.lic }}
   networks:
    - network: { get_param: mgmt_net }
    - port:  { get_resource: fgt_left_port }
    - subnet:  { get_resource: right_subnet }
#    - port:  { get_resource: right_port }

 association_fgt:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: fgt_floating_ip }
      server_id: { get_resource: fgt }

# association:
#   type: OS::Neutron::FloatingIPAssociation
#   properties:
#     floatingip_id: { get_resource: floating_ip }
#     port_id: {get_attr: [fgt, addresses, {get_param: net}, 0, port]}
 fgt_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }

 ubr_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }

 ubl_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }


 ubleft:
  type: OS::Nova::Server
  properties:
   image: { get_param: ubimage }
   flavor: m1.small
   key_name: "default"
   user_data_format: RAW
   user_data: |
     #cloud-config
     package_upgrade: true
     packages:
       - apache2-utils
       - apache2
       - tcpdump
       - iperf3
     chpasswd:
       list: |
         ubuntu:fortinet
       expire: False
     write_files:
       - content: |
           # Enable dhcp on eth1
           auto eth1
           iface eth1 inet dhcp
         path: /etc/network/interfaces.d/eth1.cfg
   name: trafleft
   security_groups: [ default ]
   networks:
    - network: { get_param: mgmt_net }
    - subnet:  { get_resource: left_subnet }

 association_left:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: ubl_floating_ip }
      server_id: { get_resource: ubleft }

 ubright:
  type: OS::Nova::Server
  properties:
   image: { get_param: ubimage }
   flavor: m1.small
   key_name: "default"
   user_data_format: RAW
   user_data: |
     #cloud-config
     package_upgrade: true
     packages:
       - apache2-utils
       - apache2
       - tcpdump
       - iperf3
     chpasswd:
       list: |
         ubuntu:fortinet
       expire: False
     write_files:
       - content: |
           # Enable dhcp on eth1
           auto eth1
           iface eth1 inet dhcp
         path: /etc/network/interfaces.d/eth1.cfg
   name: trafright
   security_groups: [ default ]
   networks:
    - network: { get_param: mgmt_net }
    - subnet:  { get_resource: right_subnet }


 association_right:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: ubr_floating_ip }
      server_id: { get_resource: ubright }

      
outputs:
 fgt-info:
    description: IP address to access of the FGT
    value: { get_attr: [ fgt_floating_ip,  floating_ip_address ] }
 left-info:
    description: IP address to access left ubuntu machine 
    value: { get_attr: [ ubl_floating_ip,  floating_ip_address ] }
 right-info:
    description: IP address to access right ubuntu machine 
    value: { get_attr: [ ubr_floating_ip,  floating_ip_address ] }
